TOP=../../../../..
DIRNAME=src/modules/OGIModules/OGIcommon/inst_tmpl

TSRCS = vector_l_t.cc vector_ptr_t.cc vector_EST_IVector.cc


CPPSRCS = $(TSRCS)

SRCS = $(CPPSRCS)
OBJS = $(CPPSRCS:.cc=.o)
FILES = $(SRCS) Makefile


ALL = .buildlib $(BUILD_DIRS)

include $(TOP)/config/common_make_rules

